Repository sonata-project/SonataUserBundle, pull requests merged in 2020-11, with the labels that each got.

#1272 Change ContainerAwareCommand to Command
  src/Command/TwoStepVerificationCommand.php
Labels: major

#1263 Allow to use "symfony/mailer" within `Mailer`
  UPGRADE-4.x.md
  composer.json
  src/Mailer/Mailer.php
  tests/Mailer/MailerTest.php
Labels: minor

#1288 :bug: Remove duplicate translation on nl
  src/Resources/translations/SonataUserBundle.nl.xliff
Labels: patch
