Repository sonata-project/SonataUserBundle, pull requests merged in 2020-07, with the labels that each got.

#1192 Bump PHP < 7.2
  composer.json
Labels: minor

#1194 Fix API route names
  src/Controller/Api/GroupController.php
  src/Controller/Api/UserController.php
  tests/Functional/Routing/RoutingTest.php
Labels: patch

#1196 Use service ids instead of controller paths at API routing config definitions
  src/Resources/config/routing/api.xml
Labels: minor

#1195 Fix passing "format" parameter to API routes
  src/Controller/Api/GroupController.php
  src/Controller/Api/UserController.php
  tests/Functional/Routing/RoutingTest.php
Labels: patch

#1183 Make SonataEasyExtends optional
  UPGRADE-4.x.md
  composer.json
  docs/reference/installation.rst
  src/DependencyInjection/SonataUserExtension.php
  tests/DependencyInjection/SonataUserExtensionTest.php
  tests/Functional/App/AppKernel.php
Labels: minor

#1202 Fix routing parameter placeholders
  src/Controller/Api/UserController.php
  tests/Functional/Routing/RoutingTest.php
Labels: patch

#1200 Use XML for ReST API routing
  composer.json
  src/Controller/Api/GroupController.php
  src/Controller/Api/UserController.php
  src/Resources/config/routing/api.xml
Labels: pedantic
