Repository sonata-project/SonataUserBundle, pull requests merged in 2021-02, with the labels that each got.

#1323 Fix getPager return type on Document
  src/Document/GroupManager.php
  src/Document/UserManager.php
Labels: patch

#1325 Add support for "doctrine/common:^3"
  composer.json
  src/DependencyInjection/SonataUserExtension.php
  src/Entity/UserManagerProxy.php
  tests/Entity/UserManagerProxyTest.php
Labels: minor

#1330 Use description in suggest
  composer.json
Labels: pedantic

#1335 Leverage `$this` binding in anonymous functions
  tests/Entity/GroupManagerTest.php
  tests/Entity/UserManagerTest.php
Labels: pedantic
