Repository sonata-project/SonataUserBundle, pull requests merged in 2021-12, with the labels that each got.

#1439 Deprecate ReST API
  UPGRADE-4.x.md
  src/Controller/Api/GroupController.php
  src/Controller/Api/Legacy/GroupController.php
  src/Controller/Api/Legacy/UserController.php
  src/Controller/Api/UserController.php
  src/DependencyInjection/SonataUserExtension.php
  src/Document/GroupManager.php
  src/Document/UserManager.php
  src/Entity/GroupManager.php
  src/Entity/UserManager.php
  src/Form/Type/ApiGroupType.php
  src/Form/Type/ApiUserType.php
  src/Model/GroupManagerInterface.php
  src/Model/UserManagerInterface.php
  src/Serializer/UserSerializerHandler.php
  tests/Controller/Api/GroupControllerTest.php
  tests/Controller/Api/UserControllerTest.php
  tests/Entity/GroupManagerTest.php
  tests/Entity/UserManagerTest.php
  tests/Serialization/SerializationTest.php
Labels: minor

#1430 Update login.html.twig
  composer.json
  src/Resources/views/Admin/Security/Resetting/checkEmail.html.twig
  src/Resources/views/Admin/Security/Resetting/request.html.twig
  src/Resources/views/Admin/Security/Resetting/reset.html.twig
  src/Resources/views/Admin/Security/login.html.twig
Labels: patch, Needs: Changelog note

#1446 Deprecate Google Authenticator integration
  src/Command/TwoStepVerificationCommand.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataUserExtension.php
  src/GoogleAuthenticator/Helper.php
  src/GoogleAuthenticator/InteractiveLoginListener.php
  src/GoogleAuthenticator/RequestListener.php
Labels: minor

#1444 Upgrade to Sonata 4
  composer.json
  src/Admin/Model/GroupAdmin.php
  src/Admin/Model/UserAdmin.php
  src/DependencyInjection/Configuration.php
  src/Resources/config/admin.xml
  src/Resources/views/Admin/Security/Resetting/checkEmail.html.twig
  src/Resources/views/Admin/Security/Resetting/request.html.twig
  src/Resources/views/Admin/Security/Resetting/reset.html.twig
  src/Resources/views/Admin/Security/login.html.twig
  src/Security/EditableRolesBuilder.php
  src/Security/RolesBuilder/AdminRolesBuilder.php
  src/Security/RolesBuilder/SecurityRolesBuilder.php
  tests/Action/CheckEmailActionTest.php
  tests/Action/LoginActionTest.php
  tests/Action/RequestActionTest.php
  tests/Action/ResetActionTest.php
  tests/Action/SendEmailActionTest.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Security/EditableRolesBuilderTest.php
  tests/Security/RolesBuilder/AdminRolesBuilderTest.php
  tests/Security/RolesBuilder/SecurityRolesBuilderTest.php
Labels: major

#1456 Move to PHP configuration format
  src/DependencyInjection/SonataUserExtension.php
  src/Resources/config/actions.php
  src/Resources/config/actions.xml
  src/Resources/config/admin.php
  src/Resources/config/admin.xml
  src/Resources/config/admin_mongodb.php
  src/Resources/config/admin_mongodb.xml
  src/Resources/config/admin_orm.php
  src/Resources/config/admin_orm.xml
  src/Resources/config/form.php
  src/Resources/config/form.xml
  src/Resources/config/listener.php
  src/Resources/config/listener.xml
  src/Resources/config/listener_sf4.xml
  src/Resources/config/listener_sf5.xml
  src/Resources/config/mailer.php
  src/Resources/config/mailer.xml
  src/Resources/config/mongodb.php
  src/Resources/config/mongodb.xml
  src/Resources/config/orm.php
  src/Resources/config/orm.xml
  src/Resources/config/routing/admin_resetting.xml
  src/Resources/config/routing/admin_security.xml
  src/Resources/config/security.php
  src/Resources/config/security.xml
  src/Resources/config/security_acl.php
  src/Resources/config/security_acl.xml
  src/Resources/config/twig.php
  src/Resources/config/twig.xml
  src/Resources/config/util.php
  src/Resources/config/util.xml
  src/Resources/config/validator.php
  src/Resources/config/validator.xml
Labels: pedantic

#1457 Simplify Actions code
  src/Action/LoginAction.php
  src/Action/RequestAction.php
  src/Action/SendEmailAction.php
  src/Resources/config/actions.php
  tests/Action/LoginActionTest.php
  tests/Action/SendEmailActionTest.php
Labels: major

#1460 Increase PHPStan to Level 4
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.xml
  src/Action/CheckEmailAction.php
  src/Action/LoginAction.php
  src/Action/ResetAction.php
  src/Admin/Model/GroupAdmin.php
  src/Admin/Model/UserAdmin.php
  src/Document/BaseGroup.php
  src/Document/GroupManager.php
  src/Document/UserManager.php
  src/Entity/BaseGroup.php
  src/Entity/GroupManager.php
  src/Entity/UserManager.php
  src/Form/Transformer/RestoreRolesTransformer.php
  src/Form/Type/RolesMatrixType.php
  src/Form/Type/SecurityRolesType.php
  src/Model/Group.php
  src/Model/GroupInterface.php
  src/Model/User.php
  src/Model/UserInterface.php
  src/Security/EditableRolesBuilder.php
  src/Security/RolesBuilder/MatrixRolesBuilder.php
  src/Security/UserProvider.php
  src/Util/CanonicalFieldsUpdater.php
  tests/Action/RequestActionTest.php
  tests/Action/ResetActionTest.php
  tests/App/Entity/Group.php
  tests/App/Entity/User.php
  tests/Functional/Action/LoginActionTest.php
  tests/Functional/Action/RequestActionTest.php
  tests/Functional/Action/ResetActionTest.php
  tests/Functional/Admin/GroupAdminTest.php
  tests/Functional/Admin/UserAdminTest.php
Labels: major

#1462 Reduce User class fields
  UPGRADE-5.0.md
  src/Admin/Model/UserAdmin.php
  src/Document/BaseGroup.php
  src/Document/BaseUser.php
  src/Entity/BaseGroup.php
  src/Entity/BaseUser.php
  src/Model/Group.php
  src/Model/User.php
  src/Model/UserInterface.php
  src/Resources/config/doctrine/BaseUser.mongodb.xml
  src/Resources/config/doctrine/BaseUser.orm.xml
Labels: major

#1466 Psalm level 2
  psalm.xml
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataUserExtension.php
  src/Document/UserManager.php
  src/Entity/UserManager.php
  src/Form/Transformer/RestoreRolesTransformer.php
  src/Form/Type/RolesMatrixType.php
  src/Form/Type/SecurityRolesType.php
  src/Listener/UserListener.php
  src/Model/User.php
  src/Security/Authorization/Voter/UserAclVoter.php
  src/Security/EditableRolesBuilder.php
  src/Security/UserProvider.php
  src/Twig/GlobalVariables.php
  tests/App/AppKernel.php
  tests/DependencyInjection/SonataUserExtensionTest.php
  tests/Document/BaseUserTest.php
  tests/Entity/BaseUserTest.php
  tests/Form/Type/SecurityRolesTypeTest.php
  tests/Functional/Action/ResetActionTest.php
  tests/Security/UserProviderTest.php
Labels: major
