Repository sonata-project/SonataUserBundle, pull requests merged in 2022-01, with the labels that each got.

#1476 Fix serialize method
  src/Model/User.php
Labels: minor

#1480 Improve documentation for next major
  docs/reference/advanced_configuration.rst
  docs/reference/installation.rst
  docs/reference/user_impersonation.rst
Labels: docs, major

#1479 Resolve NEXT_MAJOR comments
  src/Admin/Document/UserAdmin.php
  src/Admin/Entity/UserAdmin.php
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataUserExtension.php
  src/Document/UserManager.php
  src/Entity/UserManager.php
  src/Form/Transformer/RestoreRolesTransformer.php
  src/Form/Type/SecurityRolesType.php
  src/Resources/config/admin.php
  src/Security/Authorization/Voter/UserAclVoter.php
  src/Security/EditableRolesBuilder.php
  src/Security/EditableRolesBuilderInterface.php
  src/Security/UserProvider.php
  src/SonataUserBundle.php
  src/Twig/GlobalVariables.php
  tests/Form/Transformer/RestoreRolesTransformerTest.php
  tests/Form/Type/SecurityRolesTypeTest.php
  tests/Security/EditableRolesBuilderTest.php
Labels: major

#1481 Improve configuration
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/SonataUserExtension.php
  src/Resources/config/twig.php
  src/Resources/views/Admin/Core/user_block.html.twig
  src/Resources/views/Admin/Field/impersonating.html.twig
  src/Twig/GlobalVariables.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/DependencyInjection/SonataUserExtensionTest.php
Labels: major

#1485 Use Font Awesome 5 icons
  src/Resources/views/Admin/Core/user_block.html.twig
  src/Resources/views/Admin/Field/impersonating.html.twig
  src/Resources/views/Admin/Security/Resetting/checkEmail.html.twig
  src/Resources/views/Admin/Security/Resetting/request.html.twig
  src/Resources/views/Admin/Security/login.html.twig
Labels: major

#1486 Mark tests final
  tests/Action/CheckEmailActionTest.php
  tests/Action/CheckLoginActionTest.php
  tests/Action/LoginActionTest.php
  tests/Action/LogoutActionTest.php
  tests/Action/RequestActionTest.php
  tests/Action/ResetActionTest.php
  tests/Action/SendEmailActionTest.php
  tests/Admin/Document/UserAdmin.php
  tests/Admin/Entity/UserAdmin.php
  tests/DependencyInjection/ConfigurationTest.php
  tests/Document/BaseUserTest.php
  tests/Document/User.php
  tests/Entity/BaseUserTest.php
  tests/Entity/User.php
  tests/Form/Transformer/RestoreRolesTransformerTest.php
  tests/Form/Type/SecurityRolesTypeTest.php
  tests/Functional/Action/LoginActionTest.php
  tests/Functional/Action/LogoutActionTest.php
  tests/Functional/Action/RequestActionTest.php
  tests/Functional/Action/ResetActionTest.php
  tests/Mailer/MailerTest.php
  tests/Resources/XliffTest.php
  tests/Security/Authorization/Voter/UserAclVoterTest.php
  tests/Security/EditableRolesBuilderTest.php
  tests/Security/UserProviderTest.php
Labels: pedantic

#1488 Ensure emails are sent to correct address with html
  tests/Functional/Action/RequestActionTest.php
Labels: pedantic
