Repository sonata-project/SonataUserBundle, pull requests merged in 2022-10, with the labels that each got.

#1567 fix: add UniqueEntity constraint to username field.
  src/Resources/config/validation.xml
Labels: patch

#1573 Bump rector
  composer.json
Labels: pedantic

#1572 Change password field to PasswordType.
  src/Admin/Model/UserAdmin.php
Labels: minor

#1575 Fix psalm
  tests/custom_bootstrap.php
Labels: pedantic

#1577 Fix psalm and deprecation
  composer.json
  src/Security/RolesBuilder/AdminRolesBuilder.php
  tests/custom_bootstrap.php
Labels: patch
