Repository sonata-project/SonataUserBundle, pull requests merged in 2023-05, with the labels that each got.

#1640 DevKit updates for 5.x branch
  .github/workflows/documentation.yaml
  .readthedocs.yaml
  docs/conf.py
  docs/reference/roles_matrix.rst
  docs/requirements.txt
Labels: automerge, dev-kit

#1641 Up rector to 0.16
  composer.json
Labels: pedantic

#1642 DevKit updates for 5.x branch
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#1643 Support form-extensions 2.0
  composer.json
Labels: minor

#1644 Release 5.8.0
  CHANGELOG.md
Labels: dev-kit
