Repository sonata-project/SonataUserBundle, pull requests merged in 2023-03, with the labels that each got.

#1596 DevKit updates for 5.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  Makefile
  composer.json
  psalm-baseline.xml
  psalm.xml
  rector.php
  src/Action/CheckEmailAction.php
  src/Action/LoginAction.php
  src/Action/RequestAction.php
  src/Action/ResetAction.php
  src/Admin/Model/UserAdmin.php
  src/Command/ActivateUserCommand.php
  src/Command/ChangePasswordCommand.php
  src/Command/CreateUserCommand.php
  src/Command/DeactivateUserCommand.php
  src/Command/DemoteUserCommand.php
  src/Command/PromoteUserCommand.php
  src/Document/UserManager.php
  src/Entity/UserManager.php
  src/Form/Type/ResettingFormType.php
  src/Form/Type/RolesMatrixType.php
  src/Listener/LastLoginListener.php
  src/Listener/UserListener.php
  src/Mailer/Mailer.php
  src/Model/User.php
  src/Security/Authorization/Voter/UserAclVoter.php
  src/Security/RolesBuilder/AdminRolesBuilder.php
  src/Security/RolesBuilder/MatrixRolesBuilder.php
  src/Security/RolesBuilder/SecurityRolesBuilder.php
  src/Security/UserProvider.php
  src/Twig/GlobalVariables.php
  src/Twig/RolesMatrixExtension.php
  src/Validator/UserInitializer.php
  tests/Security/UserProviderTest.php
Labels: minor

#1599 Allow doctrine/collections 2.x
  composer.json
Labels: minor

#1603 Allow doctrine annotations 2.0
  composer.json
Labels: pedantic

#1605 Update psalm to v5
  composer.json
  psalm.xml
  src/Form/Type/ResetPasswordRequestFormType.php
  src/Form/Type/ResettingFormType.php
  src/Form/Type/RolesMatrixType.php
Labels: pedantic

#1606 Improve doctrine versions and configuration
  composer.json
  src/Resources/config/doctrine/BaseUser.mongodb.xml
  src/Resources/config/doctrine/BaseUser.orm.xml
  tests/App/AppKernel.php
  tests/App/Entity/User.php
  tests/App/config/config.yaml
  tests/App/config/config_sf4.yaml
  tests/App/config/config_sf5.yaml
  tests/App/config/config_sf6.yaml
  tests/App/config/config_sonata_block_v4.yaml
  tests/App/config/routes.yaml
  tests/App/templates/.gitkeep
Labels: minor

#1610 Drop DAMA 6
  composer.json
Labels: pedantic

#1611 Use attributes on docs
  docs/reference/installation.rst
  tests/App/Entity/User.php
Labels: docs

#1616 Add edit button to admin list page
  src/Admin/Model/UserAdmin.php
Labels: patch

#1615 Fix xml validation for mongodb
  src/Resources/config/doctrine/BaseUser.mongodb.xml
Labels: patch
