Repository sonata-project/SonataUserBundle, pull requests merged in 2023-06, with the labels that each got.

#1646 Add support for BlockBundle 5.0
  .github/workflows/test.yaml
  composer.json
Labels: minor

#1647 Release 5.9.0
  CHANGELOG.md
Labels: dev-kit

#1648 Cleanup older upgrade files
  UPGRADE-4.x.md
  UPGRADE-5.x.md
Labels: pedantic

#1649 Update rector
  composer.json
Labels: pedantic

#1651 UserListener: use event_listener instead of subscriber
  src/Listener/UserListener.php
  src/Resources/config/mongodb.php
  src/Resources/config/orm.php
Labels: patch
