Repository sonata-project/SonataUserBundle, pull requests merged in 2023-02, with the labels that each got.

#1587 Roles matrix group by admin and admin group
  src/Resources/views/Form/roles_matrix.html.twig
  src/Security/RolesBuilder/AdminRolesBuilder.php
  src/Security/RolesBuilder/RolesBuilderInterface.php
  src/Twig/RolesMatrixExtension.php
  tests/Security/RolesBuilder/AdminRolesBuilderTest.php
  tests/Twig/RolesMatrixExtensionTest.php
Labels: minor

#1590 Document typo
  UPGRADE-5.0.md
Labels: docs

#1595 Fix build
  src/Action/LoginAction.php
  src/Action/ResetAction.php
  tests/Action/RequestActionTest.php
Labels: pedantic
