Repository sonata-project/SonataUserBundle, pull requests merged in 2023-04, with the labels that each got.

#1621 Register UserListener for ORM and ODM
  src/Admin/Model/UserAdmin.php
  src/Model/User.php
  src/Resources/config/listener.php
  src/Resources/config/mongodb.php
  src/Resources/config/orm.php
Labels: patch

#1620 Check if user has access to its profile before generating link
  src/Resources/views/Admin/Core/user_block.html.twig
Labels: patch

#1624 fix(#1623): fix xmlns and xmlns:xsi values in BaseUser.mongodb.xml
  src/Resources/config/doctrine/BaseUser.mongodb.xml
Labels: patch

#1627 Check for is granted impersonator on Symfony >= 5.4
  src/Resources/views/Admin/Core/user_block.html.twig
Labels: patch

#1626 Split validation specific to the storage
  src/DependencyInjection/Compiler/ValidationCompilerPass.php
  src/DependencyInjection/SonataUserExtension.php
  src/Resources/config/storage-validation/mongodb.xml
  src/Resources/config/storage-validation/orm.xml
  src/Resources/config/validation.xml
  src/SonataUserBundle.php
  tests/DependencyInjection/Compiler/ValidationCompilerPassTest.php
Labels: patch

#1628 Fix ORM xmlns
  src/Resources/config/doctrine/BaseUser.orm.xml
Labels: patch

#1634 DevKit updates for 5.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#1635 DevKit updates for 6.x branch
  .github/workflows/auto-merge-dev-kit.yaml
Labels: automerge

#1636 DevKit updates for 5.x branch
  README.md
Labels: automerge

#1637 Fix CHANGELOG
  CHANGELOG.md
Labels: pedantic
