Repository sonata-project/SonataUserBundle, pull requests merged in 2024-06, with the labels that each got.

#1687 Bump rector
  composer.json
Labels: pedantic

#1688 DevKit updates for 5.x branch
  .github/workflows/documentation.yaml
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
Labels: automerge, dev-kit

#1689 Solve internal class usage
  src/DependencyInjection/SonataUserExtension.php
Labels: patch
