Repository sonata-project/SonataUserBundle, pull requests merged in 2024-08, with the labels that each got.

#1694 Fix SA
  src/Action/ResetAction.php
  src/Command/ActivateUserCommand.php
  src/Command/ChangePasswordCommand.php
  src/Command/CreateUserCommand.php
  src/Command/DeactivateUserCommand.php
  src/Command/DemoteUserCommand.php
  src/Command/PromoteUserCommand.php
  src/DependencyInjection/SonataUserExtension.php
  src/Mailer/Mailer.php
  src/Security/RolesBuilder/AdminRolesBuilder.php
  src/Security/UserProvider.php
  tests/Functional/Action/ResetActionTest.php
  tests/Mailer/MailerTest.php
Labels: pedantic

#1695 Avoid Username/Email is passed as clear GET Parameter to CheckEmailAction on password reset process
  src/Action/CheckEmailAction.php
  src/Action/RequestAction.php
  src/DependencyInjection/SonataUserExtension.php
  src/Resources/config/actions_resetting.php
  tests/Action/CheckEmailActionTest.php
  tests/Action/RequestActionTest.php
Labels: minor

#1697 DevKit updates for 5.x branch
  .github/FUNDING.yml
Labels: automerge, dev-kit
