Repository sonata-project/SonataUserBundle, pull requests merged in 2025-05, with the labels that each got.

#1707 DevKit updates for 5.x branch
  phpstan.neon.dist
Labels: automerge, dev-kit

#1710 Bump psalm and phpstan
  composer.json
  phpstan-baseline.neon
  phpstan.neon.dist
  psalm.xml
  src/DependencyInjection/Compiler/GlobalVariablesCompilerPass.php
  src/DependencyInjection/Configuration.php
  src/Mailer/Mailer.php
  src/Resources/config/commands.php
  src/Resources/config/listener.php
  src/Resources/config/mongodb.php
  src/Resources/config/orm.php
  src/Resources/config/validator.php
  src/Twig/RolesMatrixExtension.php
  src/Util/TokenGenerator.php
  tests/Action/LoginActionTest.php
  tests/Action/RequestActionTest.php
  tests/Admin/Model/UserAdminTest.php
  tests/App/AppKernel.php
  tests/App/Entity/User.php
  tests/DependencyInjection/SonataUserExtensionTest.php
  tests/Form/Type/ResettingFormTypeTest.php
  tests/Functional/Command/ActivateUserCommandTest.php
  tests/Functional/Command/ChangePasswordCommandTest.php
  tests/Functional/Command/CreateUserCommandTest.php
  tests/Functional/Command/DeactivateUserCommandTest.php
  tests/Functional/Command/DemoteUserCommandTest.php
  tests/Functional/Command/PromoteUserCommandTest.php
  tests/Mailer/MailerTest.php
  tests/Security/UserProviderTest.php
Labels: minor

#1712 Fix phpstan
  phpstan-baseline.neon
Labels: pedantic

#1713 5.15.0
  CHANGELOG.md
Labels: pedantic

#1714 DevKit updates for 5.x branch
  .github/workflows/lint.yaml
  .github/workflows/qa.yaml
  .github/workflows/symfony-lint.yaml
  .github/workflows/test.yaml
  Makefile
Labels: automerge, dev-kit
